### ISSUE TITLE
from loss.mgl import mixed_gradient_error    from inference_plot import make_fig

### ISSUE THREAD

**Issue by xiaoqiangpeng** [venkatesh-thiru/Deep-Harmonization#2]
from loss.mgl import mixed_gradient_error and
from inference_plot import make_fig cannot find the corresponding library installation, how can I solve this problem?

**Comment by venkatesh-thiru** [comment]
I have added the following 2 files to the training directory which should fix this import error

* https://github.com/venkatesh-thiru/Deep-Harmonization/blob/main/training/loss/mgl/__init__.py
* https://github.com/venkatesh-thiru/Deep-Harmonization/blob/main/training/inference_plot.py

Feel free to open this issue again if required.

**Comment by xiaoqiangpeng** [comment]
Hello, author. When I run training_loop.py, I get an error message: ModuleNotFoundError: No module named 'loss.mgl'. I try to install loss.mgl, but it says ERROR: Could not find a version that satisfies the requirement loss.mgl (from versions: none) ERROR: No matching distribution found for loss.mgl. I cannot find the loss.mgl library at https://pypi.org/. Is there something wrong with that link?

**Comment by xiaoqiangpeng** [comment]
I successfully installed pip install loss and pip install mgl

**Comment by venkatesh-thiru** [comment]
loss.mgl is not a library, it is a custom loss function which I wrote for my experiments. Please make sure that you have updated the code base, and you can find a file called ``` \training\loss\mgl\__init__.py```. The ```___init__.py``` script contain the  implementation for the Mixed Gradient Error loss function as found in this paper : https://arxiv.org/pdf/1911.09428

**Comment by xiaoqiangpeng** [comment]
I appreciate your reply. Thank you.

**Comment by xiaoqiangpeng** [comment]
Hello author, I encountered some unknown problems during the training process. For example, in the `training/config.py` file, what files should be under the `/training/model_checkpoints` and `/training/SRF`paths? Can you help me solve it? Thank you!
```
cfg.checkpoint_path = r"/data_fast/venkatesh/s2l8h/training/model_checkpoints/AttUNets"
cfg.bandpass_model_path = "/data_fast/venkatesh/s2l8h/training/SRF/models"
cfg.resume_weight_path = "/data_fast/venkatesh/s2l8h/training/model_checkpoints/AttUNets/AUNet - No SA No CA.pth"
```

**Comment by venkatesh-thiru** [comment]
```cfg.checkpoint_path``` should have the folder to which the training checkpoints are saved. ```cfg.resume_weight_path``` vairable should point to a saved checkpoint, in case you would want to resume training. This is irrelevant if ```cfg.resume_training``` is set to ```False```.

During the early phase of experiments i performed band pass adjustments using XGBoost models as a preprocessing step. I discontinued this approach as it didnt work out in my case. These XGBoost models were supposed to be under```/training/SRF```. The cfg.band_pass parameter determines whether to do the band pass adjustments during the data loading process. In a nutshell, The variable ```cfg.bandpass_model_path``` is not relevent if ```cfg.band_pass``` is set to false.

**Comment by xiaoqiangpeng** [comment]
I appreciate your reply. Thank you.

**Comment by xiaoqiangpeng** [comment]
Dear author, I encountered the following error. No files were found under the `DATA_L2_cloudless_patches` path, and I did not find the path in your code. Could you please help me solve it? Thank you.
```
Traceback (most recent call last):
  File "E:\Harmonization\training\training_loop.py", line 297, in <module>
    epoch_loss = train()
  File "E:\Harmonization\training\training_loop.py", line 127, in train
    for i, batch in enumerate(tqdm(train_loader)):
  File "D:\Anaconda\envs\Har\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\Har\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\Har\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\Har\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\Har\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Harmonization\training\Dataset.py", line 85, in __getitem__
    data_dict = self.read_data(row)
  File "E:\Harmonization\training\Dataset.py", line 61, in read_data
    patch_path = glob.glob(os.path.join(self.patch_dir, "*", "*", f"{patch_id}*"))[0]
IndexError: list index out of range
```

**Comment by venkatesh-thiru** [comment]
The ```training/DATA_L2_cloudless_patches``` should ideally contain the dataset. I havent included the data set in the github repo, or haven't uploaded them anywhere considering the size of the dataset (approx. 78k patches ≈ 65GB +). However, i have provided with the meta-data for the dataset at : https://github.com/venkatesh-thiru/Deep-Harmonization/blob/main/training/train_test_validation_patch_extended_final.csv

There you can fine the required meta-data for each patch in the respective columns like

Date of Acquisition : date
MGRS tile : location
Polygon of the patch (in the respective MGRS tile CRS) : geometry

You would need the patch files in a specific format in order for the dataloader to process it. The assumption is that each patch is a h5 file with 3 numpy arrays:

```"s2_image"``` : bands from Sentinel-2
```"l8_image"``` : bands from Landsat-8
```"l8_pan"``` : panchromatic image for the equivalent ```"l8_image"```
 
I have not included the data acquisition or preprocessing pipeline because, when i started working on the project I was using the landsatxplore package to acquire the dataset (https://github.com/yannforget/landsatxplore/tree/master). However, the library got deprecated after a backend change in the USGS STAC-API.

Later on I, made a script to acquire data from Sentinel-2 and Landsat-8 from the AWS-S3 bucket (https://github.com/venkatesh-thiru/Deep-Harmonization/blob/main/inference/download_images.py). You might have to modify the script here in order to transform them into the desired format. I will not be working on it considering my availability.

**Comment by xiaoqiangpeng** [comment]
I appreciate your reply. Thank you.
